export const apiUrl = "https://bp.lawclerk.legal";

const apiUrlPrefix = `${apiUrl}/api/v1`;

export const baseUrl = "/api"

export const apiConstant = {
  application_version: apiUrlPrefix + "/application_version",
  sign_up: apiUrlPrefix + "/sign_up",
  checkEmail: apiUrlPrefix + "/check_email",
  set_password: apiUrlPrefix + "/set_password",
  sign_in: apiUrlPrefix + "/sign_in",
  forgot_password: apiUrlPrefix + "/forgot_password",
  reset_password: apiUrlPrefix + "/reset_password",
  employees: apiUrlPrefix + "/employees",
  dropdowndepartment: apiUrlPrefix + "/dropdown/department",
  dropdownRole: apiUrlPrefix + "/dropdown/role",
  roleanddepartment: apiUrlPrefix + "/employees/employee_department_and_role",
  reporting_person: apiUrlPrefix + "/dropdown/reporting_person",
  reporting_employee: apiUrlPrefix + "/employees/reporting_employee",
  intervier_details: apiUrlPrefix + "/positions/intervier_details",
  interviewer: apiUrlPrefix + "/dropdown/interviewer",
  dropdowngender: apiUrlPrefix + "/dropdown/gender",
  workingHours: apiUrlPrefix + "/dropdown/working_hrs",
  homeHeader: apiUrlPrefix + "/home/header_index",
  openingDetails: apiUrlPrefix + "/positions",
  approve: apiUrlPrefix + "/positions/approve",
  archiveEmployees: apiUrlPrefix + "/employees/archive",
  declineReason: apiUrlPrefix + "/positions/decline_reason",
  dropdowncandidate_status: apiUrlPrefix + "/dropdown/candidate_status",
  candidates: apiUrlPrefix + "/candidates",
  positions: apiUrlPrefix + "/positions",
  show_position_on_link: apiUrlPrefix + "/positions/show_position_on_link",
  candidate_create: apiUrlPrefix + "/candidates/candidate_create",
  position_status: apiUrlPrefix + "//dropdown/position_status",
  update_status: apiUrlPrefix + "/positions/update_status",
  positionModel: apiUrlPrefix + "/positions",
  organisationsLogoUpload: apiUrlPrefix + "/organisations/logo_upload",
  editOrgName: apiUrlPrefix + "/organisations/edit_org_name",
  setRole: apiUrlPrefix + "/master/set_role",
  interviewStatus: apiUrlPrefix + "/dropdown/interview_status",
  updateInterviewRound: apiUrlPrefix + "/candidates/update_interview_round",
  interviewList: apiUrlPrefix + "/candidates/interview_list",
  addInterviewRound: apiUrlPrefix + "/candidates/add_interview_round",
  showInterview: apiUrlPrefix + "/candidates/show_interview",
  saveAsDraft: apiUrlPrefix + "/positions/save_as_draft",
  candidateStatus: apiUrlPrefix + "/dropdown/candidate_status",
  UpdateCandidate: apiUrlPrefix + "/candidates/update_candidate",
  rejecteddocuments: apiUrlPrefix + "/candidate_documents/rejected_documents",
  createofferletter: apiUrlPrefix + "/candidates/create_offer_letter",
  sendinvalidmail: apiUrlPrefix + "/candidate_documents/send_invalid_mail",
  pendingmail: apiUrlPrefix + "/candidate_documents/send_pending_mail",
  documentList: apiUrlPrefix + "/candidate_documents/document_list",
  candidateDocuments: apiUrlPrefix + "/candidate_documents",
  createMasterDepartment: apiUrlPrefix + "/masters/create_department",
  masterDepartment: apiUrlPrefix + "/masters/department",
  disableMasterDepartment: apiUrlPrefix + "/masters/disable_department",
  updateMasterDepartment: apiUrlPrefix + "/masters/update_department",
  masterLeave: apiUrlPrefix + "/masters/leave",
  updateMasterLeave: apiUrlPrefix + "/masters/leave_update",
  createMasterLeave: apiUrlPrefix + "/masters/leave_create",
  disableMasterLeave: apiUrlPrefix + "/masters/leave_disable",
  createMasterWorkShift: apiUrlPrefix + "/masters/create_working_hour",
  updateMasterWorkShift: apiUrlPrefix + "/masters/update_working_hour",
  disableMasterWorkShift: apiUrlPrefix + "/masters/disable_working_hour",
  masterWorkShift: apiUrlPrefix + "/masters/working_hour",
  createMasterHoliday: apiUrlPrefix + "/masters/holiday_create",
  masterHoliday: apiUrlPrefix + "/masters/holiday",
  updateMasterHoliday: apiUrlPrefix + "/masters/holiday_update",
  disableMasterHoliday: apiUrlPrefix + "/masters/holiday_disable",
  masterDocumentCategory: apiUrlPrefix + "/masters/document_category",
  createMasterDocumentCategory:
    apiUrlPrefix + "/masters/create_document_category",
  updateMasterDocumentCategory:
    apiUrlPrefix + "/masters/update_document_category",
  deleteMasterDocumentCategory:
    apiUrlPrefix + "/masters/disable_document_category",
  mastersrole: apiUrlPrefix + "/masters/role",
  masterscreaterole: apiUrlPrefix + "/masters/create_role",
  mastersupdate_role: apiUrlPrefix + "/masters/update_role",
  mastersdisablerole: apiUrlPrefix + "/masters/disable_role",
  masterDocumentType: apiUrlPrefix + "/masters/document_type",
  createMasterDocumentType: apiUrlPrefix + "/masters/create_document_type",
  updateMasterDocumentType: apiUrlPrefix + "/masters/update_document_type",
  disableMasterDocumentType: apiUrlPrefix + "/masters/disable_document_type",
  getTiles: apiUrlPrefix + "/dashboard/tiles_data",
  getBirthDayWishes: apiUrlPrefix + "/dashboard/birthday_wishes",
  getWorkAnniversary: apiUrlPrefix + "/dashboard/work_anniversary",
  getTodaysTask: apiUrlPrefix + "/dashboard/todays_task",
  deleteDocumentCategoryDoc:
    apiUrlPrefix + "/masters/disable_document_category",
  homeHeaderIndex: apiUrlPrefix + "/home/header_index",
  changePassword: apiUrlPrefix + "/change_password",

  //menu
  getMenuItems: baseUrl + "/DynamicMenuItem/GetDynamicMenuItem/1",
  getFooterList: baseUrl + "/FooterMenu/GetDynamicFooterItem",
  sectionOne: baseUrl + "/HomePageSectionsData/GetHomePageSectionsData",
  sectionTwo: baseUrl + "/HomePageSections/GetHomePageSections",
  getVideoItems: baseUrl + "/HomePageBannerVideo/GetHomePageBannerVideo",
  sectionThree: baseUrl + "/HomePageOtherSectionData/GetHomePageOtherSectionsData",
};

// api/HomePageBannerVideo/GetHomePageBannerVideo